os: windows
language: python
python:
  - 3.9
before_install:
      - choco install python3
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      - python -m pip install --upgrade pip wheel
script:
  - pytest
install:
  pip install -r requirements.txt
virtualenv:
  system_site_packages: true